# Generated by Django 3.2.8 on 2021-10-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20211025_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydjobs',
            old_name='Comapany',
            new_name='Company',
        ),
    ]
